name: convert txt to json

on:
  push:
    paths:
      - "songs.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: run convert
        run: node convert.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: commit json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "auto update json" || echo "no changes"
          git push
