name: deploy multi branches to pages

on:
  push:
    branches:
      - hjm
      - kawaui
      - snowshir

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # ======================
      # hjm
      # ======================
      - uses: actions/checkout@v4
        with:
          ref: hjm
          path: tmp-hjm

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: |
          cd tmp-hjm
          node convert.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      # ======================
      # kawaui
      # ======================
      - uses: actions/checkout@v4
        with:
          ref: kawaui
          path: tmp-kawaui

      - run: |
          cd tmp-kawaui
          node convert.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      # ======================
      # snowshir
      # ======================
      - uses: actions/checkout@v4
        with:
          ref: snowshir
          path: tmp-snowshir

      - run: |
          cd tmp-snowshir
          node convert.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      # ======================
      # msena
      # ======================
      - uses: actions/checkout@v4
        with:
          ref: msena
          path: tmp-msena

      - run: |
          cd tmp-msena
          node convert.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      # ======================
      # workspace
      # ======================
      - name: prepare workspace
        run: mkdir public

      # TOP
      - name: create root index
        run: |
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="ja">
          <head>
            <meta charset="UTF-8">
            <title>TOP</title>
          </head>
          <body>
            <h1>ここには何もないよ</h1>
          </body>
          </html>
          EOF
          
      - name: create CNAME
        run: echo "list.kandk-vsongs.work" > public/CNAME

      # copy hjm
      - run: |
          mkdir -p public/hjm
          rsync -av --exclude='.git' --exclude='.github' tmp-hjm/ public/hjm/

      # copy kawaui
      - run: |
          mkdir -p public/kawaui
          rsync -av --exclude='.git' --exclude='.github' tmp-kawaui/ public/kawaui/

      # copy snowshir
      - run: |
          mkdir -p public/snowshir
          rsync -av --exclude='.git' --exclude='.github' tmp-snowshir/ public/snowshir/

      # copy msena
      - run: |
          mkdir -p public/msena
          rsync -av --exclude='.git' --exclude='.github' tmp-msena/ public/msena/

      # ======================
      # deploy
      # ======================
      - run: |
          cd public
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "deploy"

          git branch -M gh-pages
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git push -f origin gh-pages
